### ISSUE TITLE
Car Racing

### ISSUE THREAD

**Issue by thorion21** [thorion21/JavaBasics#2]
Starting from the design below, implement a mechanism for cars to compete against each other.

![image](https://github.com/thorion21/JavaBasics/assets/38396004/18749b04-d98d-4f9e-a691-329c5f2c3bed)

### Tasks:

- [x] Add an additional parameter in the base class `Car` called `currentCharge`
- [x] Create a function `drive` that adjusts the remaining fuel on every call
- [ ] Create a function called `race` inside the `CarAppliance` class. `race` should run until **all** cars remain without any fuel left
- [ ] (Optional): Print cars in decreasing order they finished the race (last one that remained without fuel is the winner). Format should be `<car_class_name> - <car_description>`
